title: "Welcome to docs.openwrt.melmac.net!"
description: "Documentation site for stangri's OpenWrt packages."
url: "https://docs.openwrt.melmac.net"
author:
  name: "Stan Grishin"
  email: "stangri@melmac.ca"
header_pages:
  - https-dns-proxy/
  - nebula/
  - pbr/
  - simple-adblock/
theme: minima
minima:
  skin: auto
  social_links:
    - { platform: github,  user_url: "https://github.com/stangri" }
    - { platform: facebook, user_url: "https://www.facebook.com/stangri.openwrt/" }
    - { platform: twitter, user_url: "https://twitter.com/stangri" }
plugins:
  - jemoji
